# Generated by Django 5.2.8 on 2025-12-21 17:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-is_active', 'name']},
        ),
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RenameField(
            model_name='banktransaction',
            old_name='tx_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='description',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='title',
            field=models.CharField(default='Legacy transaction', max_length=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
