# Generated by Django 5.2.8 on 2025-12-21 17:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vehicletransaction',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RenameField(
            model_name='vehicletransaction',
            old_name='tx_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='vehicletransaction',
            name='description',
        ),
        migrations.AddField(
            model_name='vehicletransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicletransaction',
            name='title',
            field=models.CharField(default='Legacy transaction', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicletransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='vehicletransaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='assets.vehicle'),
        ),
        migrations.DeleteModel(
            name='VehicleAsset',
        ),
    ]
