# Generated by Django 5.2.8 on 2026-01-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='apply_vat',
            field=models.BooleanField(default=False),
        ),
    ]
